---
General:
  amp: true
  device: cuda:0
  task: gan-ves-seg
  model:
    name: GanSegModel
    model_g:
      name: resnetGenerator9
    model_d: 
      name: patchGAN70x70
    model_s:
      name: DynUNet
      spatial_dims: 2
      in_channels: 1
      out_channels: 1
      kernel_size: [3,3,3,3,3]
      strides: [1,2,2,2,1]
      upsample_kernel_size: [1,2,2,2,1]
    compute_identity: false
    compute_identity_seg: true
    inference: S
Train:
  data:
    real_B:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/OCTA-500_healthy/train_
    real_A:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0025
      suffix: .png
    real_A_seg:
      folder: /home/lkreitner/arterial-tree-generation/dataset_01_12_22
      suffix: gray.png
    deep:
      folder: /home/lkreitner/OCTA-seg/datasets/deep_11_11_22
      suffix: .png
  epochs: 150
  epochs_decay: 0
  save_interval: 25
  batch_size: 4
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: DiceBCELoss
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      image_only: true
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      strict_check: false
    - name: RandFlipd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      prob: 0.75
    - name: RandRotated
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      minv: 0
      maxv: 1
    - name: AsDiscreted
      keys:
      - real_A_seg
      threshold: 0.1
    - name: AddRandomGaussianNoiseChanneld
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_A_seg
      - real_B
      dtype: dtype
  post_processing:
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 256
    label: null
Validation:
  batch_size: 4
Test:
  batch_size: 1
  data:
    real_B:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      suffix: .png
    real_A:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0025
      suffix: .png
    deep:
      folder: /home/lkreitner/OCTA-seg/datasets/deep_11_11_22
      suffix: .png
  num_samples: 5
  save_images: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      allow_missing_keys: true
      image_only: true
    - name: ScaleIntensityd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      allow_missing_keys: true
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      allow_missing_keys: true
      strict_check: false
    - name: Rotate90d
      allow_missing_keys: true
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      k: 1
    - name: Flipd
      allow_missing_keys: true
      keys:
      - real_A
      - real_B
      - real_A_seg
      - deep
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - real_A_seg
      allow_missing_keys: true
      threshold: 0.1
    - name: AddRandomGaussianNoiseChanneld
      keys:
      - real_A
    - name: CastToTyped
      keys:
      - real_A
      - real_A_seg
      - real_B
      allow_missing_keys: true
      dtype: dtype
  post_processing:
    # Only if inference=S, else:
    # prediction: null
    prediction:
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 256
    label: null
Output:
  save_dir: "/home/lkreitner/OCTA-seg/results/gan-ves-seg"
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1
