---
General:
  amp: true
  device: cuda:0
  num_layers: 3
  kernel_size: 3
  task: gan-ves-seg
  model: GanSegModel
  model_g: resnetGenerator9
  model_d: patchGAN70x70
  model_s: DynUNet
Data:
  dataset_images:
  - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainB"
  - ".bmp"
  synthetic_images:
  - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA"
  - ".png"
  num_classes: 1
  class_balance:
  - 1
Train:
  dataset_path: "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/train.txt"
  epochs: 600
  epochs_decay: 100
  save_interval: 50
  batch_size: 4
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: DiceBCELoss
  lambda_cl_dice: 0
  compute_identity: false
  compute_identity_seg: true
  data_augmentation:
  - name: LoadImaged
    keys:
    - real_A
    - real_B
    image_only: true
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    minv: 0
    maxv: 1
  - name: AddChanneld
    keys:
    - real_A
    - real_B
  - name: RandFlipd
    keys:
    - real_A
    - real_B
    prob: 0.5
    spatial_axis:
    - 0
    - 1
  - name: RandRotate90d
    keys:
    - real_A
    - real_B
    prob: 0.75
  - name: RandRotated
    keys:
    - real_A
    - real_B
    prob: 1
    range_x: 0.17453292519943295
    padding_mode: zeros
  # - name: RandCropOrPadd
  #   keys:
  #   - real_A
  #   - real_B
    # prob: 1
    # min_factor: 0.25
    # max_factor: 0.25
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    minv: 0
    maxv: 1
  - name: SplitImageLabeld
    keys:
    - real_A
    - real_A_seg
  - name: AsDiscreted
    keys:
    - real_A_seg
    threshold: 0.1
  - name: Resized
    keys:
    - real_A
    shape:
    - 304
    - 304
  - name: AddRandomGaussianNoiseChanneld
    keys:
    - real_A
  - name: CastToTyped
    keys:
    - real_A
    - real_A_seg
    - real_B
    dtype: dtype
Validation:
  batch_size: 4
  dataset_path: "/home/lkreitner/OCTA-seg/datasets/synth_24_07_22/val.txt"
Test:
  batch_size: 1
  dataset_images:
  - "/home/shared/Data/DRAC22/C. Diabetic Retinopathy Grading/1. Original Images/"
  - ".png"
  dataset_path: "/home/lkreitner/OCTA-seg/datasets/DRAC_C/val_0.txt"
  num_samples: 5
  save_images: false
Output:
  save_dir: "/home/lkreitner/OCTA-seg/results/gan-ves-seg"
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1
