---
General:
  amp: true
  device: cuda:0
  num_layers: 3
  kernel_size: 3
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/results/gan-ves-seg/20221209_235844/test_100_G
      suffix: .png
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/train_
    label:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0025_OCTA-500
      suffix: .png
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/train_
  epochs: 60
  epochs_decay: 0
  val_interval: 1
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
    - name: RandFlipd
      keys:
      - image
      - label
      prob: 0.5
      spatial_axis:
      - 0
      - 1
    - name: RandRotate90d
      keys:
      - image
      - label
      prob: 0.75
    - name: RandRotated
      keys:
      - image
      - label
      prob: 1
      range_x: 0.17453292519943295
      padding_mode: zeros
    - name: RandAdjustContrastd
      keys:
      - image
      prob: 1
      gamma:
      - 0.5
      - 2.5
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
Validation:
  batch_size: 4
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images
      suffix: .png
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_
    label:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/segmentations
      suffix: .png
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 1216
      - 1216
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.1
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 160
    label:
    - name: CastToType
      dtype: uint8
Test:
  batch_size: 1
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_
  num_samples: 10
  save_images: false
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      strict_check: false
    - name: Resized
      keys:
      - image
      spatial_size:
      - 1216
      - 1216
    - name: Rotate90d
      keys:
      - image
      k: 1
    - name: Flipd
      keys:
      - image
      spatial_axis: 0
    - name: CastToTyped
      keys:
      - image
      dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 100
    label:
    - name: CastToType
      dtype: uint8
Output:
  save_dir: /home/lkreitner/OCTA-seg/results/ves-seg-supervised
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1