---
General:
  amp: true
  device: cuda:0
  num_layers: 3
  kernel_size: 3
  task: gan-ves-seg
  model: GanSegModel
  model_g: resnetGenerator9
  model_d: patchGAN70x70
  model_s: DynUNet
Data:
  num_classes: 1
  class_balance:
  - 1
Train:
  data:
    real_B:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500_healthy
      suffix: .bmp
    real_A:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0008_304x304
      suffix: .png
    real_A_seg:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0008
      suffix: .png
  epochs: 250
  epochs_decay: 50
  save_interval: 25
  batch_size: 4
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: DiceBCELoss
  lambda_cl_dice: 0
  compute_identity: false
  compute_identity_seg: true
  data_augmentation:
  - name: LoadImaged
    keys:
    - real_A
    - real_B
    - real_A_seg
    image_only: true
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    - real_A_seg
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - real_A
    - real_B
    - real_A_seg
    strict_check: false
  - name: RandFlipd
    keys:
    - real_A
    - real_B
    - real_A_seg
    prob: 0.5
    spatial_axis:
    - 0
    - 1
  - name: RandRotate90d
    keys:
    - real_A
    - real_B
    - real_A_seg
    prob: 0.75
  - name: RandRotated
    keys:
    - real_A
    - real_B
    - real_A_seg
    prob: 1
    range_x: 0.17453292519943295
    padding_mode: zeros
  # - name: Resized
  #   keys:
  #   - real_A
  #   - real_B
  #   shape:
  #   - 1216
  #   - 1216
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    - real_A_seg
    minv: 0
    maxv: 1
  # - name: RandCropOrPadd
  #   keys:
  #   - real_A
  #   - real_B
  #   - real_A_seg
  #   prob: 1
  #   min_factor: 0.25
  #   max_factor: 0.25
  # - name: SplitImageLabeld
  #   keys:
  #   - real_A
  #   - real_A_seg
  - name: AsDiscreted
    keys:
    - real_A_seg
    threshold: 0.1
  - name: AddRandomGaussianNoiseChanneld
    keys:
    - real_A
  - name: CastToTyped
    keys:
    - real_A
    - real_A_seg
    - real_B
    dtype: dtype
Validation:
  batch_size: 4
Test:
  batch_size: 1
  data:
    real_B:
      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500
      suffix: .bmp
  # dataset_path: "/home/lkreitner/OCTA-seg/datasets/DRAC_C/val_0.txt"
  num_samples: 5
  save_images: false
  inference: S
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    strict_check: false
  - name: Resized
    keys:
    - image
    - label
    shape:
    - 1216
    - 1216
  - name: Rotate90d
    keys:
    - image
    k: 1
  - name: Flipd
    keys:
    - image
    spatial_axis: 0
  - name: CastToTyped
    keys:
    - image
    dtype: dtype
Output:
  save_dir: "/home/lkreitner/OCTA-seg/results/gan-ves-seg"
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1
