---
# Configuration for optimal-oriented-flux-filter based vessel segmentation
General:
  amp: false
  device: cpu
  task: ves-seg
  model:
    name: oof
Validation:
  batch_size: 1
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images/ # Edinburgh
      split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/images/ # OCTA-500
      # split: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/val_4.txt

      suffix: .png
    label: 
      folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/segmented_images/ # Edinburgh
      split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/segmentations/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/segmentations/ # OCTA-500
      # split: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/val_4.txt

      suffix: .png
  data_augmentation:
    - name: LoadImaged
      keys:
      - image
      - label
      image_only: true
    - name: ScaleIntensityd
      keys:
      - image
      - label
      minv: 0
      maxv: 1
    - name: EnsureChannelFirstd
      keys:
      - image
      - label
      strict_check: false
    - name: Resized
      keys:
      - image
      - label
      spatial_size:
      - 368
      - 368
      mode: bilinear
    - name: Rotate90d
      keys:
      - image
      - label
      k: 1
    - name: Flipd
      keys:
      - image
      - label
      spatial_axis: 0
    - name: AsDiscreted
      keys:
      - label
      threshold: 0.5
    - name: CastToTyped
      keys:
      - image
      - label
      dtype: dtype
  post_processing:
    prediction:
    - name: AsDiscrete
      threshold: 0.58 # Edinburgh
      # threshold: 0.58 # ROSE
      # threshold: 0.65 # OCTA-500
    - name: RemoveSmallObjects
      min_size: 5 # Edinburgh
      # min_size: 54 # ROSE-1
      # min_size: 34 # OCTA-500
    label: null
Test:
  batch_size: 1
  data:
    image:
      # folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images/ # Edinburgh
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_4.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_4.txt

      folder: /home/lkreitner/OCTA-seg/datasets/OCTA-500/images # OCTA-500
      # split: /home/lkreitner/OCTA-seg/datasets/OCTA-500/val_4.txt
      # folder: /home/shared/Data/WEH_OCTA
      suffix: .png
  save_images: false
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    image_only: true
  - name: ToGrayScaled
    keys:
    - image
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    strict_check: false
  # - name: Resized
  #   keys:
  #   - image
  #   spatial_size:
  #   - 368
  #   - 368
  #   mode: bilinear
  - name: Rotate90d
    keys:
    - image
    k: 1
  - name: Flipd
    keys:
    - image
    spatial_axis: 0
  - name: CastToTyped
    keys:
    - image
    dtype: dtype
  post_processing:
    prediction:
    - name: AsDiscrete
      threshold: 0.56 # Edinburgh
      # threshold: 0.578 # ROSE
      # threshold: 0.65 # OCTA-500
    - name: RemoveSmallObjects
      min_size: 5 # Edinburgh
      # min_size: 42 # ROSE-1
      # min_size: 40 # OCTA-500
    label: null
  num_samples: 6000
  save_dir: /home/shared/OCTA_analysis/OCTA-500/oof
Output:
  save_dir: /home/lkreitner/OCTA-seg/results/oof
  save_to_disk: true
  save_to_tensorboard: false
  save_interval: 1
    

