---
General:
  amp: true
  device: cuda:0
  num_layers: 3
  kernel_size: 3
  task: ves-seg
  model:
    name: DynUNet
    spatial_dims: 2
    in_channels: 1
    out_channels: 1
    kernel_size: [3,3,3,3,3]
    strides: [1,2,2,2,1]
    upsample_kernel_size: [1,2,2,2,1]
Train:
  data:
    image:
      # - "/home/lkreitner/OCTA-CUT/results/OCTA_3x3_31-09-22/test_100/images/fake_B/"
      # - z.png
      # - "/home/lkreitner/OCTA-CUT/results/OCTA_3x3_11-10-22/test_300/images/fake_B"
      # - .png
      # - /home/lkreitner/OCTA-seg/results/cut/20221021_224019/test_150
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0008_304x304
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/synth_24_07_22/train.txt
    label:
      folder: /home/lkreitner/OCTA-seg/datasets/synth_0008
    # - /home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA_00135
    # - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA_OLD"
      suffix: .png
      split: /home/lkreitner/OCTA-seg/datasets/synth_24_07_22/train.txt
    deep:
      folder: /home/lkreitner/OCTA-seg/datasets/deep_11_11_22
    # - /home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA_00135
    # - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA_OLD"
      suffix: .png
  epochs: 30
  epochs_decay: 0
  val_interval: 1
  batch_size: 4
  lr: 0.0001
  loss: DiceBCELoss
  AT: false
  data_augmentation:
  - name: LoadImaged
    keys:
    - deep
    - image
    - label
    image_only: true
  - name: ScaleIntensityd
    keys:
    - deep
    - image
    - label
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - deep
    - image
    - label
    strict_check: false
  # - name: GaussianSmoothd
  #   keys:
  #     - deep
  #   sigma: 2
  # - name: ScaleIntensityd
  #   keys:
  #   - deep
  #   minv: 0
  #   maxv: 1
  # - name: Resized
  #   keys:
  #   - image
  #   - label
  #   spatial_size:
  #   - 1216
  #   - 1216
  - name: NoiseModeld
    keys:
      - image
  - name: RandomDecreaseResolutiond
    keys:
      - image
    max_factor: 0.25
  - name: RandFlipd
    keys:
    - image
    - label
    # - deep
    prob: 0.5
    spatial_axis:
    - 0
    - 1
  - name: RandRotate90d
    keys:
    - image
    - label
    # - deep
    prob: 0.75
  - name: RandRotated
    keys:
    - image
    - label
    # - deep
    prob: 1
    range_x: 0.17453292519943295
    padding_mode: zeros
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  # - name: RandAdjustContrastd
  #   keys:
  #   - image
  #   prob: 1
  #   gamma:
  #   - 0.5
  #   - 2.5
  - name: AsDiscreted
    keys:
    - label
    threshold: 0.1
  - name: CastToTyped
    keys:
    - image
    - label
    # - deep
    dtype: dtype
  post_processing:
    prediction:
    - name: Activations
      sigmoid: true
    - name: AsDiscrete
      threshold: 0.5
    - name: RemoveSmallObjects
      min_size: 124
    label:
    - name: CastToType
      dtype: uint8
Validation:
  batch_size: 4
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images
      suffix: .png
    label:
      folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/segmented_images
      suffix: .png
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    - label
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    - label
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    - label
    strict_check: false
  - name: Resized
    keys:
    - image
    - label
    mode: bilinear
    spatial_size:
    # - 368
    # - 368
    - 1216
    - 1216
  - name: Rotate90d
    keys:
    - image
    - label
    k: 1
  - name: Flipd
    keys:
    - image
    - label
    spatial_axis: 0
  - name: AsDiscreted
    keys:
    - label
    threshold: 0.1
  - name: CastToTyped
    keys:
    - image
    - label
    dtype: dtype
  post_processing:
    prediction:
      - name: Activations
        sigmoid: true
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 124
    label:
      - name: CastToType
        dtype: uint8
Test:
  batch_size: 1
  data:
    image:
      folder: /home/lkreitner/OCTA-seg/datasets/Munich_OCTA
      # folder: /home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainB
      suffix: .png
  num_samples: 5
  save_images: false
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    strict_check: false
  - name: Resized
    keys:
    - image
    - label
    spatial_size:
    - 1216
    - 1216
  - name: Rotate90d
    keys:
    - image
    k: 1
  - name: Flipd
    keys:
    - image
    spatial_axis: 0
  - name: CastToTyped
    keys:
    - image
    dtype: dtype
  post_processing:
    prediction:
      - name: Activations
        sigmoid: true
      - name: AsDiscrete
        threshold: 0.5
      - name: RemoveSmallObjects
        min_size: 46
    label: null
Output:
  save_dir: "/home/lkreitner/OCTA-seg/results/ves-seg"
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1