---
# Configuration for frangi-filter based vessel segmentation
General:
  amp: false
  device: cpu
  task: ves-seg
  model:
    name: frangi
Validation:
  batch_size: 1
  data:
    image:
      # folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images/ # Edinburgh
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_0.txt

      folder: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/images/ # OCTA-500
      split: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/train_0.txt

      suffix: .png
    label: 
      # folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/segmented_images/ # Edinburgh
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/segmentations/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_0.txt

      folder: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/segmentations/ # OCTA-500
      split: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/train_0.txt

      suffix: .png
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    - label
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    - label
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    - label
    strict_check: false
  - name: Rotate90d
    keys:
    - image
    - label
    k: 1
  - name: Flipd
    keys:
    - image
    - label
    spatial_axis: 0
  - name: CastToTyped
    keys:
    - image
    - label
    dtype: dtype
  post_processing:
    prediction:
    - name: AsDiscrete
      # threshold: 0.1 # Edinburgh
      # threshold: 0.3 # ROSE
      threshold: 0.74 # OCTA-500 split-0
    - name: RemoveSmallObjects
      # min_size: 8 # Edinburgh
      # min_size: 32 # ROSE-1
      min_size: 38 # OCTA-500 split-0
    label: null
Test:
  batch_size: 1
  data:
    image:
      # folder: /home/lkreitner/OCTA-seg/datasets/Edinburgh/original_images/ # Edinburgh
      # split: /home/lkreitner/OCTA-seg/datasets/Edinburgh/val_0.txt

      # folder: /home/lkreitner/OCTA-seg/datasets/ROSE-1/images/ # ROSE-1
      # split: /home/lkreitner/OCTA-seg/datasets/ROSE-1/val_0.txt

      folder: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/images/ # OCTA-500
      split: /home/lkreitner/OCTA-seg/datasets/OCTA_500_3x3/train_0.txt

      suffix: .png
  save_images: false
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    strict_check: false
  - name: Rotate90d
    keys:
    - image
    k: 1
  - name: Flipd
    keys:
    - image
    spatial_axis: 0
  - name: CastToTyped
    keys:
    - image
    dtype: dtype
  post_processing:
    prediction:
    - name: AsDiscrete
      # threshold: 0.1 # Edinburgh
      # threshold: 0.3 # ROSE
      threshold: 0.74 # OCTA-500
    - name: RemoveSmallObjects
      # min_size: 8 # Edinburgh
      # min_size: 32 # ROSE-1
      min_size: 38 # OCTA-500
    label: null
  num_samples: 5
  save_dir: /home/lkreitner/OCTA-seg/results/frangi/test
Output:
  save_dir: /home/lkreitner/OCTA-seg/results/frangi
  save_to_disk: true
  save_to_tensorboard: false
  save_interval: 1
    

