---
General:
  amp: true
  device: cuda:0
  num_layers: 3
  kernel_size: 3
  task: cut
  model: CUT
  model_g: resnetGenerator9
  model_d: patchGAN70x70
  model_s: PatchSampleF
Data:
  dataset_images:
  - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainB"
  - ".bmp"
  synthetic_images:
  - "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA"
  - ".png"
  num_classes: 1
  class_balance:
  - 1
Train:
  dataset_path: "/home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/train.txt"
  epochs: 300
  epochs_decay: 100
  save_interval: 50
  batch_size: 8
  lr: 0.0002
  loss_dg: LSGANLoss
  loss_s: NCELoss
  lambda_cl_dice: 0
  compute_identity: false
  compute_identity_seg: true
  lambda_NCE: 10.0
  nce_layers: [4,8,12,16,20]
  data_augmentation:
  - name: LoadImaged
    keys:
    - real_A
    - real_B
    image_only: true
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - real_A
    - real_B
    strict_check: false
  - name: RandFlipd
    keys:
    - real_A
    - real_B
    prob: 0.5
    spatial_axis:
    - 0
    - 1
  - name: RandRotate90d
    keys:
    - real_A
    - real_B
    prob: 0.75
  - name: Resized
    keys:
    - real_A
    shape:
    - 304
    - 304
  # - name: RandRotated
  #   keys:
  #   - real_A
  #   - real_B
  #   prob: 1
  #   range_x: 0.17453292519943295
  #   padding_mode: zeros
  # - name: RandCropOrPadd
  #   keys:
  #   - real_A
  #   - real_B
  #   prob: 1
  #   min_factor: 0.25
  #   max_factor: 0.25
  - name: ScaleIntensityd
    keys:
    - real_A
    - real_B
    minv: 0
    maxv: 1
  - name: AddRandomGaussianNoiseChanneld
    keys:
    - real_A
  - name: CastToTyped
    keys:
    - real_A
    - real_B
    dtype: dtype
Validation:
  batch_size: 4
  dataset_path: "/home/lkreitner/OCTA-seg/datasets/synth_24_07_22/val.txt"
Test:
  batch_size: 1
  dataset_images:
  - /home/lkreitner/OCTA-CUT/datasets/OCTA_3x3/trainA
  - .png
  num_samples: 500
  save_images: false
  data_augmentation:
  - name: LoadImaged
    keys:
    - image
    image_only: true
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: EnsureChannelFirstd
    keys:
    - image
    strict_check: false
  - name: Resized
    keys:
    - image
    shape:
    - 304
    - 304
  - name: Rotate90d
    keys:
    - image
    k: 1
  - name: Flipd
    keys:
    - image
    spatial_axis: 0
  - name: ScaleIntensityd
    keys:
    - image
    minv: 0
    maxv: 1
  - name: AddRandomGaussianNoiseChanneld
    keys:
    - image
  - name: CastToTyped
    keys:
    - image
    dtype: dtype
Output:
  save_dir: /home/lkreitner/OCTA-seg/results/cut
  save_to_disk: true
  save_to_tensorboard: true
  save_interval: 1
Voreen":
  image_file: ""
  voreen_tool_path: /home/shared/Software/Voreen-source/bin/
  workspace_file: /home/lkreitner/OCTA-seg/voreen/feature-vesselgraphextraction_customized_command_line.vws
  outdir: /home/lkreitner/OCTA-seg/voreen/workdir/
  tempdir: /home/lkreitner/OCTA-seg/voreen/tmpdir/
  cachedir: /home/lkreitner/OCTA-seg/voreen/cachedir/
  bulge_size: 1.5
